# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f66f285a92af824b8765522b9270bf20ec86e62cfd3205587011fde170209f617b8d88b107ecff3964858d53d90bc11aa63d28ccd769fdb6c6ed56daadbb42d

test:
  secret_key_base: b533a7a551be817cebfe183570b00d3eaa715c2e956c769915a35893c72a9d3c5e845f4cdfcd3249567a593a7c0cef6441250c8afe5bf0fac201e73107efa582

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
